import type { Metadata } from "next";
import Link from "next/link";
import { notFound } from "next/navigation";
import { ArrowLeft, ArrowRight, List } from "lucide-react";
import { ContributorLinks } from "@/components/contributor-links";
import { DocsShell } from "@/components/docs-shell";
import { ReactionBar } from "@/components/reaction-bar";
import { SiteFooter } from "@/components/site-footer";
import { getChapterBySlugs } from "@/data/library";

export const dynamic = "force-dynamic";
export async function generateMetadata({ params }: PageProps<"/books/[slug]/[chapter]">): Promise<Metadata> { const { slug, chapter } = await params; const data = await getChapterBySlugs(slug, chapter); return data ? { title: `${data.chapter.title} · ${data.book.title}`, description: data.chapter.excerpt || data.book.description || undefined } : {}; }
export default async function ChapterPage({ params }: PageProps<"/books/[slug]/[chapter]">) { const { slug, chapter: chapterSlug } = await params; const data = await getChapterBySlugs(slug, chapterSlug); if (!data) notFound(); const { book, chapter, chapterContributors, contributors, previous, next } = data; const toc = [{ title: book.title, href: `/books/${book.slug}` }, ...data.chapters.map((item) => ({ title: item.title, href: `/books/${book.slug}/${item.slug}` }))]; return <DocsShell toc={toc}><article><nav className="mb-8 flex items-center gap-2 text-xs text-muted-foreground"><Link href={`/books/${book.slug}`} className="hover:text-foreground">{book.title}</Link><span>/</span><span>{chapter.chapterNumber || chapter.position}</span></nav><header className="border-b pb-8"><p className="font-mono text-xs uppercase tracking-widest text-brand">{chapter.type} {chapter.chapterNumber}</p><h1 className="mt-3 text-4xl font-semibold tracking-[-.045em] sm:text-5xl">{chapter.title}</h1>{chapter.subtitle && <p className="mt-4 text-xl text-muted-foreground">{chapter.subtitle}</p>}<p className="mt-5 text-sm text-muted-foreground"><ContributorLinks contributors={chapterContributors.length ? chapterContributors : contributors} /> · {chapter.wordCount.toLocaleString()} words</p></header><div className="reading-copy py-10" dangerouslySetInnerHTML={{ __html: chapter.renderedHtml }} /><ReactionBar /><nav className="mt-10 grid gap-3 border-y py-5 sm:grid-cols-[1fr_auto_1fr]">{previous ? <Link href={`/books/${book.slug}/${previous.slug}`} className="flex items-center gap-2 p-3 hover:bg-muted"><ArrowLeft className="size-4" /><span><span className="block text-[10px] uppercase text-muted-foreground">Previous</span><span className="font-medium">{previous.title}</span></span></Link> : <span />}<Link href={`/books/${book.slug}`} className="grid place-items-center border px-4 py-3" aria-label="Table of contents"><List className="size-4" /></Link>{next ? <Link href={`/books/${book.slug}/${next.slug}`} className="flex items-center justify-end gap-2 p-3 text-right hover:bg-muted"><span><span className="block text-[10px] uppercase text-muted-foreground">Next</span><span className="font-medium">{next.title}</span></span><ArrowRight className="size-4" /></Link> : <span />}</nav><SiteFooter /></article></DocsShell>; }
