import type { Metadata } from "next";
import Link from "next/link";
import { notFound } from "next/navigation";
import { BookOpen, ChevronRight, LibraryBig } from "lucide-react";
import { ContributorLinks } from "@/components/contributor-links";
import { DocsShell } from "@/components/docs-shell";
import { SiteFooter } from "@/components/site-footer";
import { getBookBySlug } from "@/data/library";

export const dynamic = "force-dynamic";
export async function generateMetadata({ params }: PageProps<"/books/[slug]">): Promise<Metadata> { const { slug } = await params; const data = await getBookBySlug(slug); return data ? { title: data.book.title, description: data.book.description || undefined } : {}; }
export default async function BookPage({ params }: PageProps<"/books/[slug]">) { const { slug } = await params; const data = await getBookBySlug(slug); if (!data) notFound(); const { book, chapters, contributors } = data; return <DocsShell toc={[{ title: "About the book", href: "#about" }, { title: "Contents", href: "#contents" }]}><article><header id="about" className="grid gap-8 border-b pb-10 sm:grid-cols-[190px_1fr]"><div className="aspect-[2/3] border bg-foreground p-5 text-background shadow-[var(--shadow)]"><LibraryBig className="size-6" /><p className="mt-10 font-mono text-[9px] uppercase tracking-widest opacity-70">{book.workType}</p><p className="mt-3 text-xl font-semibold leading-tight">{book.title}</p></div><div className="self-center"><p className="font-mono text-xs uppercase tracking-widest text-brand">{book.status} · {book.language}</p><h1 className="mt-3 text-4xl font-semibold tracking-[-.045em] sm:text-5xl">{book.title}</h1>{book.subtitle && <p className="mt-3 text-xl text-muted-foreground">{book.subtitle}</p>}<p className="mt-5 text-sm text-muted-foreground"><ContributorLinks contributors={contributors} /></p><p className="mt-5 max-w-2xl leading-7 text-muted-foreground">{book.description || "Description in preparation."}</p>{book.seriesSlug && <Link href={`/series/${book.seriesSlug}`} className="mt-5 inline-flex items-center gap-2 border px-3 py-2 text-sm hover:bg-muted"><LibraryBig className="size-4" /> {book.seriesTitle}</Link>}</div></header><section id="contents" className="py-10"><div className="flex items-end justify-between border-b pb-3"><div><p className="font-mono text-[10px] uppercase tracking-widest text-brand">Table of contents</p><h2 className="mt-2 text-xl font-semibold">{chapters.length} chapters</h2></div><span className="text-xs text-muted-foreground">{chapters.reduce((sum, chapter) => sum + chapter.wordCount, 0).toLocaleString()} words</span></div><div>{chapters.map((chapter) => <Link key={chapter.id} href={`/books/${book.slug}/${chapter.slug}`} className="group flex items-center gap-4 border-b py-4 hover:bg-muted/40"><span className="grid size-10 shrink-0 place-items-center border font-mono text-xs">{chapter.chapterNumber || chapter.position}</span><div className="min-w-0 flex-1"><p className="font-medium group-hover:underline">{chapter.title}</p><p className="mt-1 text-xs text-muted-foreground">{chapter.type} · {chapter.wordCount.toLocaleString()} words</p></div><ChevronRight className="size-4 text-muted-foreground" /></Link>)}</div>{chapters[0] && <Link href={`/books/${book.slug}/${chapters[0].slug}`} className="mt-6 inline-flex items-center gap-2 bg-foreground px-4 py-2.5 text-sm font-medium text-background"><BookOpen className="size-4" /> Start reading</Link>}</section>{book.copyrightNotice && <p className="border bg-muted/40 p-4 text-xs leading-5 text-muted-foreground">{book.copyrightNotice}</p>}<SiteFooter /></article></DocsShell>; }
